global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_config:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'qdrant'
      static_configs:
        - targets: ['localhost:6333']
      metrics_path: '/metrics'

    - job_name: 'postgres'
      static_configs:
        - targets: ['localhost:9187']
    - job_name: 'node_exporter'
      static_configs:
        - targets: ['localhost:9100']
    - job_name: 'fastapi'
      static_configs:
        - targets: ['localhost:8000']
      metrics_path: '/get_msg123çà'